FROM node:20-alpine as build

workdir /app
copy package.json ./
RUN npm install
COPY . .
RUN npm run build

#---Productions---

FROM ngnix:alpine AS production
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]

FROM node:18-alpine AS development
WORKDIR /app
COPY . .
RUN npm install
CMD ["npm", "start"]